version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - '5433:5432'
    expose:
      - 5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8084:8080

  backend:
    build:
      context: ../be/demo-be
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=5432
      - DB_HOST=postgres
      # - URL_REACT=http://localhost
      # - DB_HOST=host.docker.internal
    ports:
      - 3008:1328
    expose:
      - 6000
  
  nginx: 
    image: nginx:1.23.3
    ports:
      - 3000:80
    volumes:
      - ../shop-reactjs/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/defaut.conf